// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNa7Y_ml9Ebwm44_dMjzssBXWmp__t1kg',
    appId: '1:764491896660:web:48b4eedd3b91acbec71ac1',
    messagingSenderId: '764491896660',
    projectId: 'flutter-chess-58f75',
    authDomain: 'flutter-chess-58f75.firebaseapp.com',
    storageBucket: 'flutter-chess-58f75.firebasestorage.app',
    measurementId: 'G-VTJ80ML8N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGMjCIAhWbiyoki0-TunIo_l3OFlLVH2A',
    appId: '1:764491896660:android:f629a2b1ec0acb17c71ac1',
    messagingSenderId: '764491896660',
    projectId: 'flutter-chess-58f75',
    storageBucket: 'flutter-chess-58f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb9fLOTovhFC3alf8VaDzNXHMif9Fkhak',
    appId: '1:764491896660:ios:14de7c9463ae5bf7c71ac1',
    messagingSenderId: '764491896660',
    projectId: 'flutter-chess-58f75',
    storageBucket: 'flutter-chess-58f75.firebasestorage.app',
    iosBundleId: 'com.example.chessGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb9fLOTovhFC3alf8VaDzNXHMif9Fkhak',
    appId: '1:764491896660:ios:14de7c9463ae5bf7c71ac1',
    messagingSenderId: '764491896660',
    projectId: 'flutter-chess-58f75',
    storageBucket: 'flutter-chess-58f75.firebasestorage.app',
    iosBundleId: 'com.example.chessGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNa7Y_ml9Ebwm44_dMjzssBXWmp__t1kg',
    appId: '1:764491896660:web:7c60c7790d50561fc71ac1',
    messagingSenderId: '764491896660',
    projectId: 'flutter-chess-58f75',
    authDomain: 'flutter-chess-58f75.firebaseapp.com',
    storageBucket: 'flutter-chess-58f75.firebasestorage.app',
    measurementId: 'G-GJQGB96C52',
  );
}
